# Generated by Django 2.1.2 on 2018-10-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('fame', models.CharField(blank=True, max_length=70, null=True)),
                ('mname', models.CharField(blank=True, max_length=70, null=True)),
                ('lname', models.CharField(blank=True, max_length=70, null=True)),
                ('r_street', models.CharField(blank=True, max_length=255, null=True)),
                ('r_city', models.CharField(blank=True, max_length=100, null=True)),
                ('r_state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ptype',
                'managed': False,
            },
        ),
    ]
