# Generated by Django 2.1.2 on 2018-10-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenceEvent',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('motive', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('l_street', models.CharField(blank=True, max_length=255, null=True)),
                ('l_city', models.CharField(blank=True, max_length=100, null=True)),
                ('l_state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'offence_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offender',
            fields=[
                ('opid', models.OneToOneField(db_column='opid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='front.Person')),
                ('born', models.DateField(blank=True, null=True)),
                ('died', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffenderOffence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'offender_offence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Otypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'otypes',
                'managed': False,
            },
        ),
    ]
